<a href="https://colab.research.google.com/github/satyarthi-siddharth/Titanic_Project/blob/main/Titanic_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import os
os.environ['KAGGLE_CONFIG_DIR'] = '/content/drive/My Drive/Kaggle APIs'

In [ ]:
cd /content/drive/My Drive/Kaggle APIs

/content/drive/My Drive/Kaggle APIs


In [ ]:
!kaggle competitions download -c titanic

test.csv: Skipping, found more recently modified local copy (use --force to force download)
train.csv: Skipping, found more recently modified local copy (use --force to force download)
gender_submission.csv: Skipping, found more recently modified local copy (use --force to force download)


In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/My Drive/Kaggle APIs/train.csv')
df

PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
886          887         0       2  ...  13.0000   NaN         S
887          888         1       1  ...  30.0000   B42         S
888          889         0       3  ...  23.4500   NaN         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[891 rows x 12 columns]

In [ ]:
df = df.drop(['PassengerId','Survived','Name','Ticket','Cabin'],axis=1)
df

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         3    male  22.0      1      0   7.2500        S
1         1  female  38.0      1      0  71.2833        C
2         3  female  26.0      0      0   7.9250        S
3         1  female  35.0      1      0  53.1000        S
4         3    male  35.0      0      0   8.0500        S
..      ...     ...   ...    ...    ...      ...      ...
886       2    male  27.0      0      0  13.0000        S
887       1  female  19.0      0      0  30.0000        S
888       3  female   NaN      1      2  23.4500        S
889       1    male  26.0      0      0  30.0000        C
890       3    male  32.0      0      0   7.7500        Q

[891 rows x 7 columns]

In [ ]:
df['Embarked'].fillna('S',inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    891 non-null    int64  
 1   Sex       891 non-null    object 
 2   Age       714 non-null    float64
 3   SibSp     891 non-null    int64  
 4   Parch     891 non-null    int64  
 5   Fare      891 non-null    float64
 6   Embarked  891 non-null    object 
dtypes: float64(2), int64(3), object(2)
memory usage: 48.9+ KB


In [ ]:
df

Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         3    male  22.0      1      0   7.2500        S
1         1  female  38.0      1      0  71.2833        C
2         3  female  26.0      0      0   7.9250        S
3         1  female  35.0      1      0  53.1000        S
4         3    male  35.0      0      0   8.0500        S
..      ...     ...   ...    ...    ...      ...      ...
886       2    male  27.0      0      0  13.0000        S
887       1  female  19.0      0      0  30.0000        S
888       3  female   NaN      1      2  23.4500        S
889       1    male  26.0      0      0  30.0000        C
890       3    male  32.0      0      0   7.7500        Q

[891 rows x 7 columns]

In [ ]:
df['Age'].fillna(int(df['Age'].mean()),inplace= True)

In [ ]:
numeric = df.select_dtypes(include=['float64','int64'])
numeric

Pclass   Age  SibSp  Parch     Fare
0         3  22.0      1      0   7.2500
1         1  38.0      1      0  71.2833
2         3  26.0      0      0   7.9250
3         1  35.0      1      0  53.1000
4         3  35.0      0      0   8.0500
..      ...   ...    ...    ...      ...
886       2  27.0      0      0  13.0000
887       1  19.0      0      0  30.0000
888       3  29.0      1      2  23.4500
889       1  26.0      0      0  30.0000
890       3  32.0      0      0   7.7500

[891 rows x 5 columns]

In [ ]:
categorical = df.select_dtypes(include=['object'])
categorical

Sex Embarked
0      male        S
1    female        C
2    female        S
3    female        S
4      male        S
..      ...      ...
886    male        S
887  female        S
888  female        S
889    male        C
890    male        Q

[891 rows x 2 columns]

In [ ]:
dummies = pd.get_dummies(categorical)
dummies

Sex_female  Sex_male  Embarked_C  Embarked_Q  Embarked_S
0             0         1           0           0           1
1             1         0           1           0           0
2             1         0           0           0           1
3             1         0           0           0           1
4             0         1           0           0           1
..          ...       ...         ...         ...         ...
886           0         1           0           0           1
887           1         0           0           0           1
888           1         0           0           0           1
889           0         1           1           0           0
890           0         1           0           1           0

[891 rows x 5 columns]

In [ ]:
new_df = pd.concat([dummies,numeric],axis=1)
new_df

Sex_female  Sex_male  Embarked_C  Embarked_Q  ...   Age  SibSp  Parch     Fare
0             0         1           0           0  ...  22.0      1      0   7.2500
1             1         0           1           0  ...  38.0      1      0  71.2833
2             1         0           0           0  ...  26.0      0      0   7.9250
3             1         0           0           0  ...  35.0      1      0  53.1000
4             0         1           0           0  ...  35.0      0      0   8.0500
..          ...       ...         ...         ...  ...   ...    ...    ...      ...
886           0         1           0           0  ...  27.0      0      0  13.0000
887           1         0           0           0  ...  19.0      0      0  30.0000
888           1         0           0           0  ...  29.0      1      2  23.4500
889           0         1           1           0  ...  26.0      0      0  30.0000
890           0         1           0           1  ...  32.0      0      0   7.7500

[891 rows x 10 columns]

In [ ]:
x_train = new_df.iloc[:,:9].values
x_train.shape

(891, 9)

In [ ]:
x_train

array([[ 0.,  1.,  0., ..., 22.,  1.,  0.],
       [ 1.,  0.,  1., ..., 38.,  1.,  0.],
       [ 1.,  0.,  0., ..., 26.,  0.,  0.],
       ...,
       [ 1.,  0.,  0., ..., 29.,  1.,  2.],
       [ 0.,  1.,  1., ..., 26.,  0.,  0.],
       [ 0.,  1.,  0., ..., 32.,  0.,  0.]])

In [ ]:
y_train = new_df.iloc[:,9].values
y_train.shape

(891,)

In [ ]:
y_train

array([  7.25  ,  71.2833,   7.925 ,  53.1   ,   8.05  ,   8.4583,
        51.8625,  21.075 ,  11.1333,  30.0708,  16.7   ,  26.55  ,
         8.05  ,  31.275 ,   7.8542,  16.    ,  29.125 ,  13.    ,
        18.    ,   7.225 ,  26.    ,  13.    ,   8.0292,  35.5   ,
        21.075 ,  31.3875,   7.225 , 263.    ,   7.8792,   7.8958,
        27.7208, 146.5208,   7.75  ,  10.5   ,  82.1708,  52.    ,
         7.2292,   8.05  ,  18.    ,  11.2417,   9.475 ,  21.    ,
         7.8958,  41.5792,   7.8792,   8.05  ,  15.5   ,   7.75  ,
        21.6792,  17.8   ,  39.6875,   7.8   ,  76.7292,  26.    ,
        61.9792,  35.5   ,  10.5   ,   7.2292,  27.75  ,  46.9   ,
         7.2292,  80.    ,  83.475 ,  27.9   ,  27.7208,  15.2458,
        10.5   ,   8.1583,   7.925 ,   8.6625,  10.5   ,  46.9   ,
        73.5   ,  14.4542,  56.4958,   7.65  ,   7.8958,   8.05  ,
        29.    ,  12.475 ,   9.    ,   9.5   ,   7.7875,  47.1   ,
        10.5   ,  15.85  ,  34.375 ,   8.05  , 263.    ,   8.0

In [ ]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [ ]:
df1 = pd.read_csv('/content/drive/My Drive/Kaggle APIs/test.csv')
df1

PassengerId  Pclass  ... Cabin Embarked
0            892       3  ...   NaN        Q
1            893       3  ...   NaN        S
2            894       2  ...   NaN        Q
3            895       3  ...   NaN        S
4            896       3  ...   NaN        S
..           ...     ...  ...   ...      ...
413         1305       3  ...   NaN        S
414         1306       1  ...  C105        C
415         1307       3  ...   NaN        S
416         1308       3  ...   NaN        S
417         1309       3  ...   NaN        C

[418 rows x 11 columns]

In [ ]:
df1 = df1.drop(['PassengerId','Name','Ticket','Cabin'],axis=1)

In [ ]:
df1

Pclass     Sex   Age  SibSp  Parch      Fare Embarked
0         3    male  34.5      0      0    7.8292        Q
1         3  female  47.0      1      0    7.0000        S
2         2    male  62.0      0      0    9.6875        Q
3         3    male  27.0      0      0    8.6625        S
4         3  female  22.0      1      1   12.2875        S
..      ...     ...   ...    ...    ...       ...      ...
413       3    male   NaN      0      0    8.0500        S
414       1  female  39.0      0      0  108.9000        C
415       3    male  38.5      0      0    7.2500        S
416       3    male   NaN      0      0    8.0500        S
417       3    male   NaN      1      1   22.3583        C

[418 rows x 7 columns]

In [ ]:
categorical1 = df1.select_dtypes(include=['object'])
categorical1

Sex Embarked
0      male        Q
1    female        S
2      male        Q
3      male        S
4    female        S
..      ...      ...
413    male        S
414  female        C
415    male        S
416    male        S
417    male        C

[418 rows x 2 columns]

In [ ]:
dummies1 = pd.get_dummies(categorical1)
dummies1

Sex_female  Sex_male  Embarked_C  Embarked_Q  Embarked_S
0             0         1           0           1           0
1             1         0           0           0           1
2             0         1           0           1           0
3             0         1           0           0           1
4             1         0           0           0           1
..          ...       ...         ...         ...         ...
413           0         1           0           0           1
414           1         0           1           0           0
415           0         1           0           0           1
416           0         1           0           0           1
417           0         1           1           0           0

[418 rows x 5 columns]

In [ ]:
df1['Age'].fillna(int(df1['Age'].mean()),inplace=True)  

In [ ]:
df1['Fare'].fillna(int(df1['Fare'].mean()),inplace=True)

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Pclass    418 non-null    int64  
 1   Sex       418 non-null    object 
 2   Age       418 non-null    float64
 3   SibSp     418 non-null    int64  
 4   Parch     418 non-null    int64  
 5   Fare      418 non-null    float64
 6   Embarked  418 non-null    object 
dtypes: float64(2), int64(3), object(2)
memory usage: 23.0+ KB


In [ ]:
numeric1 = df1.select_dtypes(include=['float64','int64'])
numeric1

Pclass   Age  SibSp  Parch      Fare
0         3  34.5      0      0    7.8292
1         3  47.0      1      0    7.0000
2         2  62.0      0      0    9.6875
3         3  27.0      0      0    8.6625
4         3  22.0      1      1   12.2875
..      ...   ...    ...    ...       ...
413       3  30.0      0      0    8.0500
414       1  39.0      0      0  108.9000
415       3  38.5      0      0    7.2500
416       3  30.0      0      0    8.0500
417       3  30.0      1      1   22.3583

[418 rows x 5 columns]

In [ ]:
new_df1 = pd.concat([dummies1,numeric1],axis=1)
new_df1

Sex_female  Sex_male  Embarked_C  Embarked_Q  ...   Age  SibSp  Parch      Fare
0             0         1           0           1  ...  34.5      0      0    7.8292
1             1         0           0           0  ...  47.0      1      0    7.0000
2             0         1           0           1  ...  62.0      0      0    9.6875
3             0         1           0           0  ...  27.0      0      0    8.6625
4             1         0           0           0  ...  22.0      1      1   12.2875
..          ...       ...         ...         ...  ...   ...    ...    ...       ...
413           0         1           0           0  ...  30.0      0      0    8.0500
414           1         0           1           0  ...  39.0      0      0  108.9000
415           0         1           0           0  ...  38.5      0      0    7.2500
416           0         1           0           0  ...  30.0      0      0    8.0500
417           0         1           1           0  ...  30.0      1      1   22.3583

[418 rows x 10 columns]

In [ ]:
x_test = new_df1.iloc[:,:9].values
x_test

array([[ 0. ,  1. ,  0. , ..., 34.5,  0. ,  0. ],
       [ 1. ,  0. ,  0. , ..., 47. ,  1. ,  0. ],
       [ 0. ,  1. ,  0. , ..., 62. ,  0. ,  0. ],
       ...,
       [ 0. ,  1. ,  0. , ..., 38.5,  0. ,  0. ],
       [ 0. ,  1. ,  0. , ..., 30. ,  0. ,  0. ],
       [ 0. ,  1. ,  1. , ..., 30. ,  1. ,  1. ]])

In [ ]:
y_test = new_df1.iloc[:,9].values
y_test

array([  7.8292,   7.    ,   9.6875,   8.6625,  12.2875,   9.225 ,
         7.6292,  29.    ,   7.2292,  24.15  ,   7.8958,  26.    ,
        82.2667,  26.    ,  61.175 ,  27.7208,  12.35  ,   7.225 ,
         7.925 ,   7.225 ,  59.4   ,   3.1708,  31.6833,  61.3792,
       262.375 ,  14.5   ,  61.9792,   7.225 ,  30.5   ,  21.6792,
        26.    ,  31.5   ,  20.575 ,  23.45  ,  57.75  ,   7.2292,
         8.05  ,   8.6625,   9.5   ,  56.4958,  13.4167,  26.55  ,
         7.85  ,  13.    ,  52.5542,   7.925 ,  29.7   ,   7.75  ,
        76.2917,  15.9   ,  60.    ,  15.0333,  23.    , 263.    ,
        15.5792,  29.125 ,   7.8958,   7.65  ,  16.1   , 262.375 ,
         7.8958,  13.5   ,   7.75  ,   7.725 , 262.375 ,  21.    ,
         7.8792,  42.4   ,  28.5375, 263.    ,   7.75  ,   7.8958,
         7.925 ,  27.7208, 211.5   , 211.5   ,   8.05  ,  25.7   ,
        13.    ,   7.75  ,  15.2458, 221.7792,  26.    ,   7.8958,
        10.7083,  14.4542,   7.8792,   8.05  ,   7.75  ,  23. 

In [ ]:
y_pred = model.predict(x_test)
y_pred

array([  3.55315584,   5.80501141,  32.72197313,  -2.29888437,
        18.27455242,  -0.92908921,   8.04541399,  45.9014396 ,
        21.87295699,  10.71967812,  -2.61499095,  59.83202912,
        72.46678583,  32.16747229,  69.93793322,  59.50037941,
        35.56693231,  17.53875213,   7.91238859,  19.02799781,
        84.28230741,   9.43307463,  65.53602914,  91.50699348,
       118.54394633,   1.47080655,  95.4197229 ,  17.38069884,
        60.35887342,  28.97678174,  33.53726746,  42.47003245,
        26.95081452,  27.26692109,  86.91652888,  17.80217428,
         1.40310734,   2.35142707,  -2.08814665,  -2.61499095,
        25.47743222,  61.51793086,  -3.77404839,  33.46956824,
        70.14867094,  -2.08814665,  79.14282133,   4.0273157 ,
        81.58038674,  20.44153327,  68.34331868,  48.97299988,
        56.74492571, 103.99692996,  48.65689331,  40.7427111 ,
        -3.14183524,  -2.08814665,   3.57818372,  84.10923934,
        -1.24519578,  29.24073224,  -1.35056464,   8.88

In [ ]:
y_test

array([  7.8292,   7.    ,   9.6875,   8.6625,  12.2875,   9.225 ,
         7.6292,  29.    ,   7.2292,  24.15  ,   7.8958,  26.    ,
        82.2667,  26.    ,  61.175 ,  27.7208,  12.35  ,   7.225 ,
         7.925 ,   7.225 ,  59.4   ,   3.1708,  31.6833,  61.3792,
       262.375 ,  14.5   ,  61.9792,   7.225 ,  30.5   ,  21.6792,
        26.    ,  31.5   ,  20.575 ,  23.45  ,  57.75  ,   7.2292,
         8.05  ,   8.6625,   9.5   ,  56.4958,  13.4167,  26.55  ,
         7.85  ,  13.    ,  52.5542,   7.925 ,  29.7   ,   7.75  ,
        76.2917,  15.9   ,  60.    ,  15.0333,  23.    , 263.    ,
        15.5792,  29.125 ,   7.8958,   7.65  ,  16.1   , 262.375 ,
         7.8958,  13.5   ,   7.75  ,   7.725 , 262.375 ,  21.    ,
         7.8792,  42.4   ,  28.5375, 263.    ,   7.75  ,   7.8958,
         7.925 ,  27.7208, 211.5   , 211.5   ,   8.05  ,  25.7   ,
        13.    ,   7.75  ,  15.2458, 221.7792,  26.    ,   7.8958,
        10.7083,  14.4542,   7.8792,   8.05  ,   7.75  ,  23. 

In [ ]:
from sklearn.metrics import mean_squared_error,r2_score
print(mean_squared_error(y_pred,y_test))

1817.0284421650717


In [ ]:
print(r2_score(y_test,y_pred))

0.4158784660634164
